[package]
name = "reflector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
serde = { version = "1.0.188", features = ["derive", "serde_derive"] }
toml = "0.7.6"
url = "2.4.1"
